spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:mysql://ongmysql:3306/ongdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: password
